// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap"
	"io"
)

const _ = true

type AppV2 struct {
	yap.AppV2
}
//line main.yap:7
func (this *AppV2) MainEntry() {
//line main.yap:7:1
	this.Get("/", func(ctx *yap.Context) {
//line main.yap:8:1
		ctx.Html__1(`<html><body>Hello, YA3P!</body></html>`)
	})
//line main.yap:10:1
	this.Get("/p/:id", func(ctx *yap.Context) {
//line main.yap:11:1
		var body = ctx.Body
//line main.yap:12:1
		ctx.Json__1(map[string]interface{}{"id": ctx.Param("id"), "body": body})
	})
//line main.yap:18:1
	this.Post("/", func(ctx *yap.Context) {
//line main.yap:19:1
		var body = ctx.Body
//line main.yap:20:1
		var body2, _ = io.ReadAll(ctx.Body)
//line main.yap:21:1
		ctx.Json__1(map[string]interface{}{"test": "a", "body": body, "body2": fmt.Sprintf("%s", body2)})
	})
//line main.yap:28:1
	this.Run("localhost:8082")
}
func (this *AppV2) Main() {
	yap.Gopt_AppV2_Main(this)
}
func main() {
	new(AppV2).Main()
}
